FROM maven:3.9.11-eclipse-temurin-21-alpine As build
ADD spring-petclinic /APPDATA
WORKDIR /APPDATA
RUN mvn package


FROM eclipse-temurin:25_36-jdk As runtime
RUN useradd -m -d /usr/share/mainuser -s /bin/sh divya
USER divya
COPY --from=build /APPDATA/target/*.jar /devops/divya.jar
WORKDIR /devops
EXPOSE 8080
CMD ["java","-jar", "divya.jar"]