FROM maven:3.9.11-eclipse-temurin-21-alpine As build
ADD spring-petclinic /APPDATA
WORKDIR /APPDATA
RUN mvn package


FROM eclipse-temurin:25_36-jdk As runtime
LABEL project="java project"
LABEL author="devopsteam"
ENV JAVA_HOME=/usr/lib/jvm/openjdk-17-jdk-amd64
ENV MAVEN_HOME=/opt
ARG myownuser=mainuser
RUN useradd -m -d /usr/share/mainuser -s /bin/sh ${myownuser}
USER ${myownuser}
COPY --from=build /APPDATA/target/*.jar /devops/divya.jar
WORKDIR /devops
EXPOSE 8080
CMD ["java","-jar", "divya.jar"]