apiVersion: v1
kind: Pod
metadata:
  name: nodeportpod
  labels:
    app: test
spec:
  containers:
  - name: nodeportcontainer
    image: :rekulapallydivya/javarepo:javaenv
    ports:
    - containerPort: 8080
      protocol: TCP