apiVersion: v1
kind: Pod
metadata:
  name: clusterippod
  labels:
    app: test
spec:
  containers:
  - name: clusteripcontainer
    image: jenkins/jenkins:latest
    ports:
    - containerPort: 8080
      protocol: TCP